# OrbitOS — Bootloader module
---
efiBootLoader: "grub"
kernel: "/vmlinuz-linux-zen"
img: "/initramfs-linux-zen.img"
fallback: "/initramfs-linux-zen-fallback.img"

kernelLine: ", with linux-zen"
fallbackKernelLine: ", with linux-zen (fallback)"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"

efiBootloaderId: "OrbitOS"

grubProbe: true

installEFIFallback: true
