# OrbitOS — Install base system via pacstrap
---
dontChroot: true

script:
    - command: "/usr/local/lib/orbitos/orbitos-pacstrap.sh install @@ROOT@@"
      timeout: 1800
      name: "Installing base system (pacstrap)..."
