# OrbitOS — Configure repositories in target system
---
dontChroot: false

script:
    - command: "/usr/local/lib/orbitos/orbitos-repos.sh"
      timeout: 600
      name: "Configuring Chaotic-AUR and CachyOS repositories..."
