# OrbitOS — Initialize live environment for installation
---
dontChroot: true

script:
    - command: "/usr/local/lib/orbitos/orbitos-pacstrap.sh prepare"
      timeout: 120
      name: "Preparing package repositories..."
