# OrbitOS — Welcome module
---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false

requirements:
    requiredStorage:    40
    requiredRam:        4.0
    internetCheckUrl:   https://archlinux.org
    check:
        - storage
        - ram
        - root
        - internet
    required:
        - storage
        - ram
        - root
        - internet

geoip:
    style: "none"
